services:
  CedricZiel\InstanaBundle\EventListener\RequestEventListener:
    arguments:
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2000 }
      - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishrequest }
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
      - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
